//autogenerated:yes
//nolint:revive,lll
package mavros_msgs

import (
	"github.com/instockcom/goroslib/pkg/msg"
	"github.com/instockcom/goroslib/pkg/msgs/geographic_msgs"
	"github.com/instockcom/goroslib/pkg/msgs/geometry_msgs"
	"github.com/instockcom/goroslib/pkg/msgs/std_msgs"
)

type CameraImageCaptured struct {
	msg.Package   `ros:"mavros_msgs"`
	Header        std_msgs.Header
	Orientation   geometry_msgs.Quaternion
	Geo           geographic_msgs.GeoPoint
	RelativeAlt   float32
	ImageIndex    int32
	CaptureResult int8
	FileUrl       string
}
