//autogenerated:yes
//nolint:revive,lll
package mavros_msgs

import (
	"github.com/instockcom/goroslib/pkg/msg"
	"github.com/instockcom/goroslib/pkg/msgs/std_msgs"
)

type ESCInfoItem struct {
	msg.Package  `ros:"mavros_msgs"`
	Header       std_msgs.Header
	FailureFlags uint16
	ErrorCount   uint32
	Temperature  int32
}
