//autogenerated:yes
//nolint:revive,lll
package mavros_msgs

import (
	"github.com/instockcom/goroslib/pkg/msg"
)

type ParamValue struct {
	msg.Package `ros:"mavros_msgs"`
	Integer     int64
	Real        float64
}
