//autogenerated:yes
//nolint:revive,lll
package std_msgs

import (
	"github.com/instockcom/goroslib/pkg/msg"
)

type MultiArrayLayout struct {
	msg.Package `ros:"std_msgs"`
	Dim         []MultiArrayDimension
	DataOffset  uint32
}
