//autogenerated:yes
//nolint:revive,lll
package geographic_msgs

import (
	"github.com/instockcom/goroslib/pkg/msg"
	"github.com/instockcom/goroslib/pkg/msgs/std_msgs"
	"github.com/instockcom/goroslib/pkg/msgs/uuid_msgs"
)

type RoutePath struct {
	msg.Package `ros:"geographic_msgs"`
	Header      std_msgs.Header
	Network     uuid_msgs.UniqueID
	Segments    []uuid_msgs.UniqueID
	Props       []KeyValue
}
