//autogenerated:yes
//nolint:revive,lll
package geographic_msgs

import (
	"github.com/instockcom/goroslib/pkg/msg"
	"github.com/instockcom/goroslib/pkg/msgs/uuid_msgs"
)

type GetGeoPathReq struct {
	msg.Package `ros:"geographic_msgs"`
	Start       GeoPoint
	Goal        GeoPoint
}

type GetGeoPathRes struct {
	msg.Package `ros:"geographic_msgs"`
	Success     bool
	Status      string
	Plan        GeoPath
	Network     uuid_msgs.UniqueID
	StartSeg    uuid_msgs.UniqueID
	GoalSeg     uuid_msgs.UniqueID
	Distance    float64
}

type GetGeoPath struct {
	msg.Package `ros:"geographic_msgs"`
	GetGeoPathReq
	GetGeoPathRes
}
