//autogenerated:yes
//nolint:revive,lll
package vision_msgs

import (
	"github.com/instockcom/goroslib/pkg/msg"
	"github.com/instockcom/goroslib/pkg/msgs/std_msgs"
)

type Detection3DArray struct {
	msg.Package `ros:"vision_msgs"`
	Header      std_msgs.Header
	Detections  []Detection3D
}
