//autogenerated:yes
//nolint:revive,lll
package geometry_msgs

import (
	"github.com/instockcom/goroslib/pkg/msg"
)

type Pose struct {
	msg.Package `ros:"geometry_msgs"`
	Position    Point
	Orientation Quaternion
}
