//autogenerated:yes
//nolint:revive,lll
package std_srvs

import (
	"github.com/instockcom/goroslib/pkg/msg"
)

type EmptyReq struct {
	msg.Package `ros:"std_srvs"`
}

type EmptyRes struct {
	msg.Package `ros:"std_srvs"`
}

type Empty struct {
	msg.Package `ros:"std_srvs"`
	EmptyReq
	EmptyRes
}
