//autogenerated:yes
//nolint:revive,lll
package control_msgs

import (
	"github.com/instockcom/goroslib/pkg/msg"
	"github.com/instockcom/goroslib/pkg/msgs/std_msgs"
	"github.com/instockcom/goroslib/pkg/msgs/trajectory_msgs"
)

type JointTrajectoryControllerState struct {
	msg.Package `ros:"control_msgs"`
	Header      std_msgs.Header
	JointNames  []string
	Desired     trajectory_msgs.JointTrajectoryPoint
	Actual      trajectory_msgs.JointTrajectoryPoint
	Error       trajectory_msgs.JointTrajectoryPoint
}
