//autogenerated:yes
//nolint:revive,lll
package control_msgs

import (
	"github.com/instockcom/goroslib/pkg/msg"
	"github.com/instockcom/goroslib/pkg/msgs/std_msgs"
)

type JointJog struct {
	msg.Package   `ros:"control_msgs"`
	Header        std_msgs.Header
	JointNames    []string
	Displacements []float64
	Velocities    []float64
	Duration      float64
}
