//autogenerated:yes
//nolint:revive,lll
package actionlib_msgs

import (
	"time"

	"github.com/instockcom/goroslib/pkg/msg"
)

type GoalID struct {
	msg.Package `ros:"actionlib_msgs"`
	Stamp       time.Time
	Id          string
}
