//autogenerated:yes
//nolint:revive,lll
package audio_common_msgs

import (
	"github.com/instockcom/goroslib/pkg/msg"
)

type AudioData struct {
	msg.Package `ros:"audio_common_msgs"`
	Data        []uint8
}
