//autogenerated:yes
//nolint:revive,lll
package diagnostic_msgs

import (
	"github.com/instockcom/goroslib/pkg/msg"
	"github.com/instockcom/goroslib/pkg/msgs/std_msgs"
)

type DiagnosticArray struct {
	msg.Package `ros:"diagnostic_msgs"`
	Header      std_msgs.Header
	Status      []DiagnosticStatus
}
