//autogenerated:yes
//nolint:revive,lll
package tf2_msgs

import (
	"github.com/instockcom/goroslib/pkg/msg"
)

type FrameGraphReq struct {
	msg.Package `ros:"tf2_msgs"`
}

type FrameGraphRes struct {
	msg.Package `ros:"tf2_msgs"`
	FrameYaml   string
}

type FrameGraph struct {
	msg.Package `ros:"tf2_msgs"`
	FrameGraphReq
	FrameGraphRes
}
